-- KIWI Supabase central setup
-- Run this once in Supabase SQL Editor after creating feedback and orders.

alter table public.feedback add column if not exists rating integer;
alter table public.feedback add column if not exists comment text;
alter table public.feedback add column if not exists name text;
alter table public.feedback add column if not exists table_number integer;

alter table public.orders add column if not exists table_number integer;
alter table public.orders add column if not exists items jsonb;
alter table public.orders add column if not exists total numeric;
alter table public.orders add column if not exists status text default 'pending';

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  table_number integer,
  meta jsonb
);
alter table public.analytics_events enable row level security;
drop policy if exists "Allow public analytics insert" on public.analytics_events;
create policy "Allow public analytics insert" on public.analytics_events
for insert to anon with check (true);

-- Keep public data write-only. The admin reads through the protected RPC below.
drop policy if exists "Allow public feedback insert" on public.feedback;
create policy "Allow public feedback insert" on public.feedback
for insert to anon with check (true);
drop policy if exists "Allow public order insert" on public.orders;
create policy "Allow public order insert" on public.orders
for insert to anon with check (true);

create or replace function public.kiwi_admin_data(p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if p_pin is distinct from '2580' then
    raise exception 'Unauthorized';
  end if;

  select jsonb_build_object(
    'stats', jsonb_build_object(
      'orders_count', (select count(*) from public.orders),
      'feedback_count', (select count(*) from public.feedback),
      'avg_rating', coalesce((select round(avg(rating)::numeric,2) from public.feedback),0)
    ),
    'feedback', coalesce((select jsonb_agg(to_jsonb(f) order by f.created_at desc) from (select id,created_at,table_number,rating,name,comment from public.feedback order by created_at desc limit 100) f),'[]'::jsonb),
    'orders', coalesce((select jsonb_agg(to_jsonb(o) order by o.created_at desc) from (select id,created_at,table_number,items,total,status from public.orders order by created_at desc limit 100) o),'[]'::jsonb),
    'best_sellers', coalesce((
      select jsonb_agg(jsonb_build_object('name',x.name,'qty',x.qty) order by x.qty desc)
      from (
        select item->>'name' as name, sum(coalesce((item->>'qty')::numeric,0)) as qty
        from public.orders o, jsonb_array_elements(coalesce(o.items,'[]'::jsonb)) item
        group by item->>'name'
        order by qty desc
        limit 10
      ) x
    ),'[]'::jsonb)
  ) into result;
  return result;
end;
$$;

revoke all on function public.kiwi_admin_data(text) from public;
grant execute on function public.kiwi_admin_data(text) to anon;

-- Required API grants (RLS policies alone are not enough if table privileges were restricted).
grant usage on schema public to anon;
grant insert on table public.feedback to anon;
grant insert on table public.orders to anon;
grant insert on table public.analytics_events to anon;
